#! /bin/sh
bspc rule -r "*"

###---Autostart---###

run()
{
    pgrep $1 || exec $* &
}

setup_polybar()
{
    for m in $(xrandr -q | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar -r example &
    done
}

run sxhkd
feh --bg-fill --randomize /games/wallpapers
killall polybar; setup_polybar
run redshift-gtk -l 31.8:35.2
run flameshot
run albert
run picom --config ~/.config/picom.conf


setxkbmap -option grp:caps_toggle us,il &


###---MONITORS---###
# bspc monitor eDP-1 -d 1 2 3 4 5 6 7
bspc monitor -d 0 1 2 3 
bspc monitor DP-4 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#8000ff"
bspc config presel_feedback_color	"#8000ff"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 6

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a albert border=off 
